version: "3.9"
services:
  threejs-app:
    platform: linux/amd64  # ✅ CORRECT placement
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: npm run dev -- --host

